name: Azure Terraform GitOps (OCI back-end)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'azure/**'
  pull_request_target:
    types:
      - closed
    branches:
      - main
    paths:
      - 'azure/**'

  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: 'Azure Terraform pipeline'
    runs-on: self-hosted
    permissions:
      contents: read
      pull-requests: write
      packages: read
      repository-projects: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Clone Azure Orchestrator
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: git clone https://${GH_TOKEN}@github.com/iblake/clickops-orchestrator-azure.git ORCH

    - name: Load Runner Environment
      run: |
        # Load variables from runner environment (more secure)
        source /opt/actions-runner/.github-runner-env
        echo "✅ ARM credentials loaded from runner environment"

    - name: Replace Subscription ID in config files
      run: |
        source /opt/actions-runner/.github-runner-env
        find ${{ github.workspace }}/azure/fra -name '*.json' -exec sed -i "s|__SUBSCRIPTION_ID__|$ARM_SUBSCRIPTION_ID|g" {} \;
        echo "✅ Subscription ID replaced in configuration files"

    - name: Azure CLI Login
      run: |
        # Use variables from runner environment
        source /opt/actions-runner/.github-runner-env
        az login --service-principal \
          --username "$ARM_CLIENT_ID" \
          --password "$ARM_CLIENT_SECRET" \
          --tenant "$ARM_TENANT_ID" > /dev/null 2>&1
        az account set --subscription "$ARM_SUBSCRIPTION_ID" > /dev/null 2>&1
        echo "✅ Azure login successful"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.1
        terraform_wrapper: true

    - name: Render versions.tf from template
      run: |
        # Use variables from runner environment
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        envsubst < versions.tf.template > versions.tf
        terraform fmt versions.tf

    - name: Terraform Init
      run: |
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        terraform init

    - name: Terraform Format
      id: format
      if: github.event_name == 'pull_request'
      run: |
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        terraform fmt -check

    - name: Terraform Validate
      id: validate
      if: github.event_name == 'pull_request'
      run: |
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        terraform validate -no-color

    - name: Validate SSH Key Availability (OCI Pattern)
      id: ssh-key
      run: |
        SSH_KEY_PATH="$HOME/.ssh/azure_vm_key.pub"
        if [ ! -f "$SSH_KEY_PATH" ]; then
          echo "SSH public key not found at $SSH_KEY_PATH"
          echo "Please ensure your self-hosted runner has SSH keys configured"
          echo "Run: ssh-keygen -t rsa -b 4096 -f $HOME/.ssh/azure_vm_key -N ''"
          exit 1
        fi
        echo "SSH key found and ready"
        echo "SSH_PUBLIC_KEY=$(cat $SSH_KEY_PATH)" >> $GITHUB_OUTPUT

    - name: Mask SSH Key in logs
      run: |
        SSH_KEY=$(cat $HOME/.ssh/azure_vm_key.pub)
        echo "::add-mask::$SSH_KEY"

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      id: plan
      run: |
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        CONFIG_DIR=${{ github.workspace }}/azure/fra
        VARS=$(find $CONFIG_DIR -name '*.json')
        echo "$VARS"
        terraform plan -detailed-exitcode -no-color $(for i in $VARS; do echo "-var-file $i"; done) -out=tfplan.binary
        echo "plan-exit-code=$?" >> $GITHUB_OUTPUT

    - name: Post PR comment
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      env:
        PLAN: ${{ steps.plan.outputs.stdout }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format 🖌 \`${{ steps.format.outcome }}\`
          #### Terraform Validate 🤖 \`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖 \`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`terraform
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pushed by: @${{ github.actor }}*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });

    - name: Notify Slack on success
      if: success() && github.event_name == 'pull_request'
      run: |
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "✅ Terraform plan succeeded on PR #${{ github.event.number }}",
            "blocks": [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*✅ Terraform Plan Succeeded*\n*PR:* <${{ github.event.pull_request.html_url }}|#${{ github.event.number }} - ${{ github.event.pull_request.title }}>\n*Author:* @${{ github.actor }}\n*Status:* Format ✓ | Validate ✓ | Plan ✓"
              }
            }]
          }'

    - name: Notify Slack on failure
      if: failure()
      run: |
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d '{
            "text": "❌ Terraform workflow FAILED",
            "blocks": [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*❌ Terraform Workflow FAILED*\n*PR:* <${{ github.event.pull_request.html_url }}|#${{ github.event.number }}>\n*Logs:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow logs>\n*Author:* @${{ github.actor }}"
              }
            }]
          }'

    - name: Terraform Apply (on PR merge)
      id: apply
      if: >
        github.event_name == 'pull_request_target' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true
      run: |
        source /opt/actions-runner/.github-runner-env
        cd ${{ github.workspace }}/ORCH
        CONFIG_DIR=${{ github.workspace }}/azure/fra
        VARS=$(find $CONFIG_DIR -name '*.json')
        terraform apply -auto-approve $(for i in $VARS; do echo "-var-file $i"; done)

    - name: Get deployed resources info
      id: resources
      if: >
        github.event_name == 'pull_request_target' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true &&
        success()
      run: |
        cd ${{ github.workspace }}/ORCH
        CONFIG_DIR=${{ github.workspace }}/azure/fra

        # Extract VMs
        VMS=$(find $CONFIG_DIR -name 'compute*.json' -exec jq -r '.virtual_machines | to_entries[] | "• " + .value.name' {} \; 2>/dev/null | sort -u)

        # Extract VNets
        VNETS=$(find $CONFIG_DIR -name '*network.json' -not -name '*security*' -exec jq -r '.networks | to_entries[] | "• " + .value.name + " (" + .value.cidr + ")"' {} \; 2>/dev/null | sort -u)

        # Extract NSGs
        NSGS=$(find $CONFIG_DIR -name '*security*.json' -exec jq -r '.security_groups | keys[] | "• " + .' {} \; 2>/dev/null | sort -u)

        # Extract Resource Groups
        RGS=$(find $CONFIG_DIR -name '*resource*.json' -exec jq -r '.resource_groups | to_entries[] | "• " + .value.name + " [" + .value.location + "]"' {} \; 2>/dev/null | sort -u)

        # Get Public IPs using Azure CLI
        RG_NAME=$(jq -r '.resource_groups | to_entries[0].value.name' $CONFIG_DIR/project-resource-groups.json)
        PUBLIC_IPS=$(az network public-ip list --resource-group "$RG_NAME" --query "[].{name:name, ip:ipAddress}" -o tsv 2>/dev/null | awk '{print "• " $1 ": " $2}' || echo "")

        # Build resources output
        echo "resources<<EOF" >> $GITHUB_OUTPUT
        echo "Resource Groups:" >> $GITHUB_OUTPUT
        echo "${RGS:-  None}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Virtual Networks:" >> $GITHUB_OUTPUT
        echo "${VNETS:-  None}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Network Security Groups:" >> $GITHUB_OUTPUT
        echo "${NSGS:-  None}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Virtual Machines:" >> $GITHUB_OUTPUT
        echo "${VMS:-  None}" >> $GITHUB_OUTPUT
        echo "" >> $GITHUB_OUTPUT
        echo "Public IPs:" >> $GITHUB_OUTPUT
        echo "${PUBLIC_IPS:-  Retrieving...}" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Notify Slack on Apply success
      if: >
        github.event_name == 'pull_request_target' &&
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true &&
        success()
      run: |
        RESOURCES="${{ steps.resources.outputs.resources }}"
        curl -X POST ${{ secrets.SLACK_WEBHOOK_URL }} \
          -H 'Content-Type: application/json' \
          -d "{
            \"text\": \"✅ Azure Infrastructure Deployed Successfully\",
            \"blocks\": [{
              \"type\": \"section\",
              \"text\": {
                \"type\": \"mrkdwn\",
                \"text\": \"*✅ Azure Infrastructure Deployed*\n*PR:* <${{ github.event.pull_request.html_url }}|#${{ github.event.number }} - ${{ github.event.pull_request.title }}>\n*Author:* @${{ github.actor }}\n*Region:* eastus\n\n*Deployed Resources:*\n\`\`\`\n${RESOURCES}\n\`\`\`\"
              }
            }, {
              \"type\": \"context\",
              \"elements\": [{
                \"type\": \"mrkdwn\",
                \"text\": \"<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View deployment logs>\"
              }]
            }]
          }"